FROM golang:1.17-buster 

RUN apt update && apt install git \
    binutils-gold \
    curl \
    g++ \
    gcc \
    gnupg \
    make

RUN mkdir /app

COPY ../../ /tmp

RUN ls -al /tmp

COPY ./air-install.sh /tmp/install.sh

RUN chmod +x /tmp/install.sh

RUN bash /tmp/install.sh

# Install VSCode Golang Extension 
RUN go get -v github.com/uudashr/gopkgs/v2/cmd/gopkgs
RUN go get -v github.com/ramya-rao-a/go-outline
RUN go get -v github.com/cweill/gotests/gotests
RUN go get -v github.com/fatih/gomodifytags
RUN go get -v github.com/josharian/impl
RUN go get -v github.com/haya14busa/goplay/cmd/goplay
RUN go get -v github.com/go-delve/delve/cmd/dlv
RUN go get -v github.com/go-delve/delve/cmd/dlv@master
RUN go get -v honnef.co/go/tools/cmd/staticcheck
RUN go get -v golang.org/x/tools/gopls

# Install packages
RUN go get entgo.io/ent/cmd/ent
RUN go get -u github.com/spf13/cobra@latest

RUN useradd -ms /bin/bash golang

COPY ./go.mod /app/go.mod
COPY ./go.sum /app/go.sum
COPY ./cmd /app/cmd
#COPY ./.air.linux.conf /app/.air.linux.conf
#RUN go install github.com/directoryxx/fiber-clean-template/cmd

# RUN go get github.com/oxequa/realize
WORKDIR /app

RUN go mod download
#RUN cd /app/cmd && go install github.com/fusesuphasin/mongofiber/go-fiber/cmd

USER golang

CMD ["air"]